version: '3.8'

services:
  spark-master:
    container_name: spark-master
    image: bi4yourdata/cluster-spark-jupyterlab:latest
    entrypoint: ['./entrypoint.sh', 'master']
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'

  spark-history-server:
    container_name: spark-history
    image: bi4yourdata/cluster-spark-jupyterlab:latest
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  spark-worker:
    image: bi4yourdata/cluster-spark-jupyterlab:latest
    entrypoint: ['./entrypoint.sh', 'worker']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events

  jupyterlab:
    container_name: jupyterlab
    image: bi4yourdata/cluster-spark-jupyterlab:latest
    entrypoint: ['./entrypoint.sh', 'jupyterlab']
    ports:
      - '8888:8888'
    volumes:
      - ./dados:/opt/spark/data
      - ./jobs:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    depends_on:
      - spark-master
    
volumes:
  spark-logs:
